services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ws-gateway
    networks:
      - interface
  api:
    build: ./api
    networks:
      - interface
      - kafka
  ws-gateway:
    build: ./ws-gateway
    networks:
      - interface
      - kafka
networks:
  interface:
    driver: bridge
  kafka:
    driver: bridge
