services:
 kafka-topic-init:
  image: bitnamilegacy/kafka:3.4
  environment:
   - KAFKA_TOPIC_PARTITIONS=3
   - KAFKA_REPLICATION_FACTOR=3
  entrypoint: ["/bin/sh", "-c"]
  command: >
    kafka-topics.sh --bootstrap-server kafka-0:9092 --create --if-not-exists
    --topic queue --partitions $$KAFKA_TOPIC_PARTITIONS --replication-factor $$KAFKA_REPLICATION_FACTOR
    &&
    kafka-topics.sh  --bootstrap-server kafka-0:9092 --create --if-not-exists
    --topic result --partitions $$KAFKA_TOPIC_PARTITIONS --replication-factor $$KAFKA_REPLICATION_FACTOR
  restart: "no"
  depends_on:
   kafka-0:
    condition: service_healthy
   kafka-1:
    condition: service_healthy
   kafka-2:
    condition: service_healthy
  networks:
   - kafka
 kafka-0:
  image: bitnamilegacy/kafka:3.4
  ports:
   - "9094:9094"
  environment:
   - KAFKA_ENABLE_KRAFT=yes
   - ALLOW_PLAINTEXT_LISTENER=yes
   - KAFKA_CFG_NODE_ID=0
   - KAFKA_CFG_PROCESS_ROLES=broker,controller
   - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
   - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
   - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
   - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
   - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  volumes:
   - kafka_0_data:/bitnami/kafka
  networks:
   - kafka
  healthcheck:
   test: ["CMD", "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
   interval: 30s
   start_period: 30s
 kafka-1:
  image: bitnamilegacy/kafka:3.4
  ports:
   - "9084:9094"
  environment:
   - KAFKA_ENABLE_KRAFT=yes
   - ALLOW_PLAINTEXT_LISTENER=yes
   - KAFKA_CFG_NODE_ID=1
   - KAFKA_CFG_PROCESS_ROLES=broker,controller
   - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
   - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
   - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
   - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
   - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9084
   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  volumes:
   - kafka_1_data:/bitnami/kafka
  networks:
   - kafka
  healthcheck:
   test: ["CMD", "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
   interval: 30s
   start_period: 30s
 kafka-2:
  image: bitnamilegacy/kafka:3.4
  ports:
   - "9074:9094"
  environment:
   - KAFKA_ENABLE_KRAFT=yes
   - ALLOW_PLAINTEXT_LISTENER=yes
   - KAFKA_CFG_NODE_ID=2
   - KAFKA_CFG_PROCESS_ROLES=broker,controller
   - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
   - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
   - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
   - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
   - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9074
   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  volumes:
   - kafka_2_data:/bitnami/kafka
  networks:
   - kafka
  healthcheck:
   test: ["CMD", "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
   interval: 30s
   start_period: 30s
 api:
  environment:
   - KAFKA_BOOTSTRAP_SERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
  networks:
   - kafka
 ws-gateway:
  environment:
   - KAFKA_BOOTSTRAP_SERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
  networks:
   - kafka
volumes:
 kafka_0_data:
 kafka_1_data:
 kafka_2_data:
networks:
 kafka:
    driver: bridge
