spring.application.name=Api
server.port=8080
server.servlet.context-path=/api
server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB

s3.server=${MINIO_SERVER}
s3.port=${MINIO_PORT}
s3.profile.root.user=${MINIO_ROOT_USER}
s3.profile.root.password=${MINIO_ROOT_PASSWORD}
s3.profile.presigned.user=${MINIO_PRESIGNED_USER}
s3.profile.presigned.password=${MINIO_PRESIGNED_PASSWORD}
s3.bucket.client.name=${MINIO_CLIENT_BUCKET_NAME}
s3.bucket.result.name=${MINIO_RESULT_BUCKET_NAME}
