spring.application.name=processor

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.concurrency=${KAFKA_CONCURRENCY:1}
spring.kafka.consumer.group-id=processor

s3.server=${MINIO_SERVER}
s3.profile.root.user=${MINIO_ROOT_USER}
s3.profile.root.password=${MINIO_ROOT_PASSWORD}
s3.bucket.client.name=${MINIO_CLIENT_BUCKET_NAME}
s3.bucket.result.name=${MINIO_RESULT_BUCKET_NAME}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=10000